from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import io

def generate_pdf_report(data):
    """
    Generates a PDF report from the analysis data.
    """
    buffer = io.BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter

    # Title
    p.setFont("Helvetica-Bold", 24)
    p.drawString(50, height - 50, "Equipment Analysis Report")

    # Stats
    p.setFont("Helvetica-Bold", 14)
    p.drawString(50, height - 100, "Summary Statistics")
    
    p.setFont("Helvetica", 12)
    stats = data.get('stats', {})
    y = height - 130
    for key, value in stats.items():
        p.drawString(70, y, f"{key.replace('_', ' ').title()}: {value}")
        y -= 20

    # Distribution
    p.setFont("Helvetica-Bold", 14)
    y -= 20
    p.drawString(50, y, "Equipment Type Distribution")
    
    p.setFont("Helvetica", 12)
    y -= 30
    dist = data.get('type_distribution', {})
    for key, value in dist.items():
        p.drawString(70, y, f"{key}: {value}")
        y -= 20

    # Footer
    p.setFont("Helvetica-Oblique", 10)
    p.drawString(50, 50, "Generated by Chemical Equipment Visualizer")

    p.showPage()
    p.save()
    
    buffer.seek(0)
    return buffer
